[tool.poetry]
name = "pacup"
version = "0.1.0"
description = "Help maintainers update pacscripts"
authors = ["Sourajyoti Basak <wiz28@protonmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.4"
httpx = "^0.22.0"
rich = "^11.2.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
codespell = "^2.1.0"
isort = "^5.10.1"
mypy = "^0.931"
pre-commit = "^2.17.0"
pytest = "^7.0.1"
pyupgrade = "^2.31.0"

[tool.isort]
balanced_wrapping = true
combine_star = true
group_by_package = true
known_first_party = ["pacstall"]
lexicographical = true
profile = "black"
py_version = 38

[tool.mypy]
disallow_untyped_decorators = false
ignore_missing_imports = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
strict = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
